version: '3.7'
services:

  web:
    image: nginx:alpine
    ports:
      - "8081:80"
    volumes:
      - ./:/code
      - ./docker/conf/default.conf:/etc/nginx/conf.d/default.conf
      - ./log:/var/log/nginx



  php:
    build:
      context: ./docker
    volumes:
      - ./:/code
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    env_file:
      - app/.env



  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    env_file:
      - app/.env

